CONTIKI = ../

PROJECT_SOURCEFILES = construccion_arbol.c

$(info MY_TX_POWER_DBM is ${MY_TX_POWER_DBM})

CFLAGS += -DMY_TX_POWER_DBM=${MY_TX_POWER_DBM}


CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
